apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc
  name: nginx-svc
  namespace: my-workspace
spec:
  ports:
  - name: nginx-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dep
  type: NodePort
status:
  loadBalancer: {}
