apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: static-app
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://github.com/ukpillai89/argo.git
        targetRevision: HEAD
        path: nginx
    destination:
        server: https://kubernetes.default.svc
        namespace: my-workspace
